# Regression Predict Student Solution

© Explore Data Science Academy

---
### Honour Code

I {**YOUR NAME, YOUR SURNAME**}, confirm - by submitting this document - that the solutions in this notebook are a result of my own work and that I abide by the [EDSA honour code](https://drive.google.com/file/d/1QDCjGZJ8-FmJE3bZdIQNwnJyQKPhHZBn/view?usp=sharing).

Non-compliance with the honour code constitutes a material breach of contract.

### Predict Overview: Spain Electricity Shortfall Challenge

The government of Spain is considering an expansion of it's renewable energy resource infrastructure investments. As such, they require information on the trends and patterns of the countries renewable sources and fossil fuel energy generation. Your company has been awarded the contract to:

- 1. analyse the supplied data;
- 2. identify potential errors in the data and clean the existing data set;
- 3. determine if additional features can be added to enrich the data set;
- 4. build a model that is capable of forecasting the three hourly demand shortfalls;
- 5. evaluate the accuracy of the best machine learning model;
- 6. determine what features were most important in the model’s prediction decision, and
- 7. explain the inner working of the model to a non-technical audience.

Formally the problem statement was given to you, the senior data scientist, by your manager via email reads as follow:

> In this project you are tasked to model the shortfall between the energy generated by means of fossil fuels and various renewable sources - for the country of Spain. The daily shortfall, which will be referred to as the target variable, will be modelled as a function of various city-specific weather features such as `pressure`, `wind speed`, `humidity`, etc. As with all data science projects, the provided features are rarely adequate predictors of the target variable. As such, you are required to perform feature engineering to ensure that you will be able to accurately model Spain's three hourly shortfalls.
 
On top of this, she has provided you with a starter notebook containing vague explanations of what the main outcomes are.

<a id="cont"></a>

## Table of Contents

<a href=#one>1. Importing Packages</a>

<a href=#two>2. Loading Data</a>

<a href=#three>3. Exploratory Data Analysis (EDA)</a>

<a href=#four>4. Data Engineering</a>

<a href=#five>5. Modeling</a>

<a href=#six>6. Model Performance</a>

<a href=#seven>7. Model Explanations</a>

 <a id="one"></a>
## 1. Importing Packages
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Importing Packages ⚡ |
| :--------------------------- |
| In this section you are required to import, and briefly discuss, the libraries that will be used throughout your analysis and modelling. |

---

In [1]:
# Libraries for data loading, data manipulation and data visulisation
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import plotly.express as px
from statsmodels.graphics.correlation import plot_corr

# Libraries for data preparation and model building
from scipy import stats
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics 
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import accuracy_score
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.metrics import mean_squared_error as MSE
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
import math
from statsmodels.graphics.correlation import plot_corr
import statsmodels.formula.api as sm
from statsmodels.formula.api import ols
from scipy.stats import pearsonr
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
# Setting global constants to ensure notebook results are reproducible
#PARAMETER_CONSTANT = ###

<a id="two"></a>
## 2. Loading the Data
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Loading the data ⚡ |
| :--------------------------- |
| In this section you are required to load the data from the `df_train` file into a DataFrame. |

---

In [2]:
df_1 = pd.read_csv('df_train.csv') # load the train data
df_2 = pd.read_csv('df_test.csv') # load the test data

#### Creating a copy of the data to avoid making permanent changes to the data

In [3]:
df_train = df_1.copy() # Copy of the train data
df_test = df_2.copy() # Copy of the test data

<a id="three"></a>
## 3. Exploratory Data Analysis (EDA)
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Exploratory data analysis ⚡ |
| :--------------------------- |
| In this section, you are required to perform an in-depth analysis of all the variables in the DataFrame. |

---

In [4]:
# look at data statistics

In [5]:
#checking the shape of the data
df_train.shape

(8763, 49)

In [6]:
df_test.shape

(2920, 48)

The shape of the train data set indcates 8763 rows and 49 columns.  
The shape of the test data set indcates 2920 rows and 48 columns.

**Note:** We will add *T* to (transpose)tranform our data by changing the diagonals of the columns and index for a better view of the columns.

In [7]:
df_train.head().T

,0,1,2,3,4
Unnamed: 0,0,1,2,3,4
time,2015-01-01 03:00:00,2015-01-01 06:00:00,2015-01-01 09:00:00,2015-01-01 12:00:00,2015-01-01 15:00:00
Madrid_wind_speed,0.666667,0.333333,1.0,1.0,1.0
Valencia_wind_deg,level_5,level_10,level_9,level_8,level_7
Bilbao_rain_1h,0.0,0.0,0.0,0.0,0.0
Valencia_wind_speed,0.666667,1.666667,1.0,1.0,1.0
Seville_humidity,74.333333,78.333333,71.333333,65.333333,59.0
Madrid_humidity,64.0,64.666667,64.333333,56.333333,57.0
Bilbao_clouds_all,0.0,0.0,0.0,0.0,2.0
Bilbao_wind_speed,1.0,1.0,1.0,1.0,0.333333
Seville_clouds_all,0.0,0.0,0.0,0.0,0.0
Bilbao_wind_deg,223.333333,221.0,214.333333,199.666667,185.0
Barcelona_wind_speed,6.333333,4.0,2.0,2.333333,4.333333
Barcelona_wind_deg,42.666667,139.0,326.0,273.0,260.0
Madrid_clouds_all,0.0,0.0,0.0,0.0,0.0
Seville_wind_speed,3.333333,3.333333,2.666667,4.0,3.0
Barcelona_rain_1h,0.0,0.0,0.0,0.0,0.0
Seville_pressure,sp25,sp25,sp25,sp25,sp25
Seville_rain_1h,0.0,0.0,0.0,0.0,0.0
Bilbao_snow_3h,0.0,0.0,0.0,0.0,0.0
Barcelona_pressure,1036.333333,1037.333333,1038.0,1037.0,1035.0
Seville_rain_3h,0.0,0.0,0.0,0.0,0.0
Madrid_rain_1h,0.0,0.0,0.0,0.0,0.0
Barcelona_rain_3h,0.0,0.0,0.0,0.0,0.0
Valencia_snow_3h,0.0,0.0,0.0,0.0,0.0
Madrid_weather_id,800.0,800.0,800.0,800.0,800.0
Barcelona_weather_id,800.0,800.0,800.0,800.0,800.0
Bilbao_pressure,1035.0,1035.666667,1036.0,1036.0,1035.333333
Seville_weather_id,800.0,800.0,800.0,800.0,800.0
Valencia_pressure,1002.666667,1004.333333,1005.333333,1009.0,NaN
Seville_temp_max,274.254667,274.945,278.792,285.394,285.513719
Madrid_pressure,971.333333,972.666667,974.0,994.666667,1035.333333
Valencia_temp_max,269.888,271.728333,278.008667,284.899552,283.015115
Valencia_temp,269.888,271.728333,278.008667,284.899552,283.015115
Bilbao_weather_id,800.0,800.0,800.0,800.0,800.0
Seville_temp,274.254667,274.945,278.792,285.394,285.513719
Valencia_humidity,75.666667,71.0,65.666667,54.0,58.333333
Valencia_temp_min,269.888,271.728333,278.008667,284.899552,283.015115
Barcelona_temp_max,281.013,280.561667,281.583667,283.434104,284.213167
Madrid_temp_max,265.938,266.386667,272.708667,281.895219,280.678437
Barcelona_temp,281.013,280.561667,281.583667,283.434104,284.213167
Bilbao_temp_min,269.338615,270.376,275.027229,281.135063,282.252063
Bilbao_temp,269.338615,270.376,275.027229,281.135063,282.252063
Barcelona_temp_min,281.013,280.561667,281.583667,283.434104,284.213167
Bilbao_temp_max,269.338615,270.376,275.027229,281.135063,282.252063
Seville_temp_min,274.254667,274.945,278.792,285.394,285.513719
Madrid_temp,265.938,266.386667,272.708667,281.895219,280.678437
Madrid_temp_min,265.938,266.386667,272.708667,281.895219,280.678437
load_shortfall_3h,6715.666667,4171.666667,4274.666667,5075.666667,6620.666667

In [8]:
df_test.head().T

,0,1,2,3,4
Unnamed: 0,8763,8764,8765,8766,8767
time,2018-01-01 00:00:00,2018-01-01 03:00:00,2018-01-01 06:00:00,2018-01-01 09:00:00,2018-01-01 12:00:00
Madrid_wind_speed,5.0,4.666667,2.333333,2.666667,4.0
Valencia_wind_deg,level_8,level_8,level_7,level_7,level_7
Bilbao_rain_1h,0.0,0.0,0.0,0.0,0.0
Valencia_wind_speed,5.0,5.333333,5.0,5.333333,8.666667
Seville_humidity,87.0,89.0,89.0,93.333333,65.333333
Madrid_humidity,71.333333,78.0,89.666667,82.666667,64.0
Bilbao_clouds_all,20.0,0.0,0.0,26.666667,26.666667
Bilbao_wind_speed,3.0,3.666667,2.333333,5.666667,10.666667
Seville_clouds_all,0.0,0.0,6.666667,6.666667,0.0
Bilbao_wind_deg,193.333333,143.333333,130.0,196.666667,233.333333
Barcelona_wind_speed,4.0,4.666667,4.0,2.333333,4.666667
Barcelona_wind_deg,176.666667,266.666667,263.333333,86.666667,283.333333
Madrid_clouds_all,0.0,0.0,0.0,0.0,0.0
Seville_wind_speed,1.0,0.666667,0.666667,1.333333,1.0
Barcelona_rain_1h,0.0,0.0,0.0,0.0,0.0
Seville_pressure,sp25,sp25,sp25,sp25,sp25
Seville_rain_1h,0.0,0.0,0.0,0.0,0.0
Bilbao_snow_3h,0,0,0,0,0
Barcelona_pressure,1017.333333,1020.333333,1023.0,1025.666667,1026.0
Seville_rain_3h,0.0,0.0,0.0,0.0,0.0
Madrid_rain_1h,0.0,0.0,0.0,0.0,0.0
Barcelona_rain_3h,0.0,0.0,0.0,0.0,0.0
Valencia_snow_3h,0,0,0,0,0
Madrid_weather_id,800.0,800.0,800.0,800.0,800.0
Barcelona_weather_id,800.0,800.333333,800.0,800.0,800.333333
Bilbao_pressure,1025.666667,1026.666667,1025.333333,1025.0,1022.333333
Seville_weather_id,800.0,800.0,800.333333,800.333333,800.0
Valencia_pressure,NaN,NaN,NaN,NaN,NaN
Seville_temp_max,284.483333,282.483333,280.816667,281.15,287.15
Madrid_pressure,1030.0,1030.333333,1030.666667,1032.333333,1032.333333
Valencia_temp_max,287.483333,284.15,282.816667,283.483333,287.15
Valencia_temp,287.483333,284.15,282.816667,283.483333,287.15
Bilbao_weather_id,801.0,721.0,800.0,801.333333,801.333333
Seville_temp,283.673333,281.673333,280.613333,279.936667,285.57
Valencia_humidity,46.333333,53.666667,42.0,45.0,41.0
Valencia_temp_min,287.483333,284.15,282.816667,283.483333,287.15
Barcelona_temp_max,287.816667,284.816667,284.483333,284.15,287.483333
Madrid_temp_max,280.816667,280.483333,276.483333,277.15,281.15
Barcelona_temp,287.356667,284.19,283.15,283.19,286.816667
Bilbao_temp_min,276.15,277.816667,276.816667,279.15,281.816667
Bilbao_temp,280.38,281.01,279.196667,281.74,284.116667
Barcelona_temp_min,286.816667,283.483333,281.816667,282.15,286.15
Bilbao_temp_max,285.15,284.15,282.15,284.483333,286.816667
Seville_temp_min,283.15,281.15,280.483333,279.15,284.483333
Madrid_temp,279.866667,279.193333,276.34,275.953333,280.686667
Madrid_temp_min,279.15,278.15,276.15,274.483333,280.15

Observations:

1. There is an unnamed column that has the same value with the index value as seen above, this column is insignificant to our use case
2. Column names have a mix of upper and lower case letters
3. All wind_deg and pressure columns are supposed to be expressed as a category according to the (features) data description on Kaggle
4. The weather id columns are insignificant to our use case

In [9]:
#checking the data type of each column in the data
print(df_train.info())

#checking if there are missing values in any column
print(df_train.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8763 entries, 0 to 8762
Data columns (total 49 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            8763 non-null   int64
 1   time                  8763 non-null   object
 2   Madrid_wind_speed     8763 non-null   float64
 3   Valencia_wind_deg     8763 non-null   object
 4   Bilbao_rain_1h        8763 non-null   float64
 5   Valencia_wind_speed   8763 non-null   float64
 6   Seville_humidity      8763 non-null   float64
 7   Madrid_humidity       8763 non-null   float64
 8   Bilbao_clouds_all     8763 non-null   float64
 9   Bilbao_wind_speed     8763 non-null   float64
 10  Seville_clouds_all    8763 non-null   float64
 11  Bilbao_wind_deg       8763 non-null   float64
 12  Barcelona_wind_speed  8763 non-null   float64
 13  Barcelona_wind_deg    8763 non-null   float64
 14  Madrid_clouds_all     8763 non-null   float64
 15  Seville_wind_speed    8763 non-null   float64
 16  Barcelona_rain_1h     8763 non-null   float64
 17  Seville_pressure      8763 non-null   object
 18  Seville_rain_1h       8763 non-null   float64
 19  Bilbao_snow_3h        8763 non-null   float64
 20  Barcelona_pressure    8763 non-null   float64
 21  Seville_rain_3h       8763 non-null   float64
 22  Madrid_rain_1h        8763 non-null   float64
 23  Barcelona_rain_3h     8763 non-null   float64
 24  Valencia_snow_3h      8763 non-null   float64
 25  Madrid_weather_id     8763 non-null   float64
 26  Barcelona_weather_id  8763 non-null   float64
 27  Bilbao_pressure       8763 non-null   float64
 28  Seville_weather_id    8763 non-null   float64
 29  Valencia_pressure     6695 non-null   float64
 30  Seville_temp_max      8763 non-null   float64
 31  Madrid_pressure       8763 non-null   float64
 32  Valencia_temp_max     8763 non-null   float64
 33  Valencia_temp         8763 non-null   float64
 34  Bilbao_weather_id     8763 non-null   float64
 35  Seville_temp          8763 non-null   float64
 36  Valencia_humidity     8763 non-null   float64
 37  Valencia_temp_min     8763 non-null   float64
 38  Barcelona_temp_max    8763 non-null   float64
 39  Madrid_temp_max       8763 non-null   float64
 40  Barcelona_temp        8763 non-null   float64
 41  Bilbao_temp_min       8763 non-null   float64
 42  Bilbao_temp           8763 non-null   float64
 43  Barcelona_temp_min    8763 non-null   float64
 44  Bilbao_temp_max       8763 non-null   float64
 45  Seville_temp_min      8763 non-null   float64
 46  Madrid_temp           8763 non-null   float64
 47  Madrid_temp_min       8763 non-null   float64
 48  load_shortfall_3h     8763 non-null   float64
dtypes: float64(45), int64(1), object(3)
memory usage: 3.3+ MB
None
Unnamed: 0                 0
time                       0
Madrid_wind_speed          0
Valencia_wind_deg          0
Bilbao_rain_1h             0
Valencia_wind_speed        0
Seville_humidity           0
Madrid_humidity            0
Bilbao_clouds_all          0
Bilbao_wind_speed          0
Seville_clouds_all         0
Bilbao_wind_deg            0
Barcelona_wind_speed       0
Barcelona_wind_deg         0
Madrid_clouds_all          0
Seville_wind_speed         0
Barcelona_rain_1h          0
Seville_pressure           0
Seville_rain_1h            0
Bilbao_snow_3h             0
Barcelona_pressure         0
Seville_rain_3h            0
Madrid_rain_1h             0
Barcelona_rain_3h          0
Valencia_snow_3h           0
Madrid_weather_id          0
Barcelona_weather_id       0
Bilbao_pressure            0
Seville_weather_id         0
Valencia_pressure       2068
Seville_temp_max           0
Madrid_pressure            0
Valencia_temp_max          0
Valencia_temp              0
Bilbao_weather_id          0
Seville_temp               0
Valencia_humidity          0
Valencia_temp_min          0
Barcelona_temp_max         0
Madrid_temp_max            0
Barcelona_temp             0
Bilbao_temp_min            0
Bilbao_temp                0
Barcelona_temp_min         0
Bilbao_temp_max            0
Seville_temp_min           0
Madrid_temp                0
Madrid_temp_min            0
load_shortfall_3h          0
dtype: int64

In [10]:
#checking the data type of each column in the data
print(df_test.info())

#checking if there are missing values in any column
print(df_test.isnull().sum());

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2920 entries, 0 to 2919
Data columns (total 48 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            2920 non-null   int64
 1   time                  2920 non-null   object
 2   Madrid_wind_speed     2920 non-null   float64
 3   Valencia_wind_deg     2920 non-null   object
 4   Bilbao_rain_1h        2920 non-null   float64
 5   Valencia_wind_speed   2920 non-null   float64
 6   Seville_humidity      2920 non-null   float64
 7   Madrid_humidity       2920 non-null   float64
 8   Bilbao_clouds_all     2920 non-null   float64
 9   Bilbao_wind_speed     2920 non-null   float64
 10  Seville_clouds_all    2920 non-null   float64
 11  Bilbao_wind_deg       2920 non-null   float64
 12  Barcelona_wind_speed  2920 non-null   float64
 13  Barcelona_wind_deg    2920 non-null   float64
 14  Madrid_clouds_all     2920 non-null   float64
 15  Seville_wind_speed    2920 non-null   float64
 16  Barcelona_rain_1h     2920 non-null   float64
 17  Seville_pressure      2920 non-null   object
 18  Seville_rain_1h       2920 non-null   float64
 19  Bilbao_snow_3h        2920 non-null   int64
 20  Barcelona_pressure    2920 non-null   float64
 21  Seville_rain_3h       2920 non-null   float64
 22  Madrid_rain_1h        2920 non-null   float64
 23  Barcelona_rain_3h     2920 non-null   float64
 24  Valencia_snow_3h      2920 non-null   int64
 25  Madrid_weather_id     2920 non-null   float64
 26  Barcelona_weather_id  2920 non-null   float64
 27  Bilbao_pressure       2920 non-null   float64
 28  Seville_weather_id    2920 non-null   float64
 29  Valencia_pressure     2466 non-null   float64
 30  Seville_temp_max      2920 non-null   float64
 31  Madrid_pressure       2920 non-null   float64
 32  Valencia_temp_max     2920 non-null   float64
 33  Valencia_temp         2920 non-null   float64
 34  Bilbao_weather_id     2920 non-null   float64
 35  Seville_temp          2920 non-null   float64
 36  Valencia_humidity     2920 non-null   float64
 37  Valencia_temp_min     2920 non-null   float64
 38  Barcelona_temp_max    2920 non-null   float64
 39  Madrid_temp_max       2920 non-null   float64
 40  Barcelona_temp        2920 non-null   float64
 41  Bilbao_temp_min       2920 non-null   float64
 42  Bilbao_temp           2920 non-null   float64
 43  Barcelona_temp_min    2920 non-null   float64
 44  Bilbao_temp_max       2920 non-null   float64
 45  Seville_temp_min      2920 non-null   float64
 46  Madrid_temp           2920 non-null   float64
 47  Madrid_temp_min       2920 non-null   float64
dtypes: float64(42), int64(3), object(3)
memory usage: 1.1+ MB
None
Unnamed: 0                0
time                      0
Madrid_wind_speed         0
Valencia_wind_deg         0
Bilbao_rain_1h            0
Valencia_wind_speed       0
Seville_humidity          0
Madrid_humidity           0
Bilbao_clouds_all         0
Bilbao_wind_speed         0
Seville_clouds_all        0
Bilbao_wind_deg           0
Barcelona_wind_speed      0
Barcelona_wind_deg        0
Madrid_clouds_all         0
Seville_wind_speed        0
Barcelona_rain_1h         0
Seville_pressure          0
Seville_rain_1h           0
Bilbao_snow_3h            0
Barcelona_pressure        0
Seville_rain_3h           0
Madrid_rain_1h            0
Barcelona_rain_3h         0
Valencia_snow_3h          0
Madrid_weather_id         0
Barcelona_weather_id      0
Bilbao_pressure           0
Seville_weather_id        0
Valencia_pressure       454
Seville_temp_max          0
Madrid_pressure           0
Valencia_temp_max         0
Valencia_temp             0
Bilbao_weather_id         0
Seville_temp              0
Valencia_humidity         0
Valencia_temp_min         0
Barcelona_temp_max        0
Madrid_temp_max           0
Barcelona_temp            0
Bilbao_temp_min           0
Bilbao_temp               0
Barcelona_temp_min        0
Bilbao_temp_max           0
Seville_temp_min          0
Madrid_temp               0
Madrid_temp_min           0
dtype: int64

Observations:

1. Valencia_pressure has 2068 null values in the train dataset and 454 null values in the test dataset.
2. The datatype 'object' indicates that the columns time, Valencia wind deg, and Seville pressure are not numerical.

In [11]:
# A look at the train data descriptive statistics
df_train.describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,8763.0,4381.000000,2529.804538,0.000000,2190.500000,4381.000000,6571.500000,8.762000e+03
Madrid_wind_speed,8763.0,2.425729,1.850371,0.000000,1.000000,2.000000,3.333333,1.300000e+01
Bilbao_rain_1h,8763.0,0.135753,0.374901,0.000000,0.000000,0.000000,0.100000,3.000000e+00
Valencia_wind_speed,8763.0,2.586272,2.411190,0.000000,1.000000,1.666667,3.666667,5.200000e+01
Seville_humidity,8763.0,62.658793,22.621226,8.333333,44.333333,65.666667,82.000000,1.000000e+02
Madrid_humidity,8763.0,57.414717,24.335396,6.333333,36.333333,58.000000,78.666667,1.000000e+02
Bilbao_clouds_all,8763.0,43.469132,32.551044,0.000000,10.000000,45.000000,75.000000,1.000000e+02
Bilbao_wind_speed,8763.0,1.850356,1.695888,0.000000,0.666667,1.000000,2.666667,1.266667e+01
Seville_clouds_all,8763.0,13.714748,24.272482,0.000000,0.000000,0.000000,20.000000,9.733333e+01
Bilbao_wind_deg,8763.0,158.957511,102.056299,0.000000,73.333333,147.000000,234.000000,3.593333e+02
Barcelona_wind_speed,8763.0,2.870497,1.792197,0.000000,1.666667,2.666667,4.000000,1.266667e+01
Barcelona_wind_deg,8763.0,190.544848,89.077337,0.000000,118.166667,200.000000,260.000000,3.600000e+02
Madrid_clouds_all,8763.0,19.473392,28.053660,0.000000,0.000000,0.000000,33.333333,1.000000e+02
Seville_wind_speed,8763.0,2.425045,1.672895,0.000000,1.000000,2.000000,3.333333,1.166667e+01
Barcelona_rain_1h,8763.0,0.128906,0.634730,0.000000,0.000000,0.000000,0.000000,1.200000e+01
Seville_rain_1h,8763.0,0.039439,0.175857,0.000000,0.000000,0.000000,0.000000,3.000000e+00
Bilbao_snow_3h,8763.0,0.031912,0.557264,0.000000,0.000000,0.000000,0.000000,2.130000e+01
Barcelona_pressure,8763.0,1377.964605,14073.140990,670.666667,1014.000000,1018.000000,1022.000000,1.001411e+06
Seville_rain_3h,8763.0,0.000243,0.003660,0.000000,0.000000,0.000000,0.000000,9.333333e-02
Madrid_rain_1h,8763.0,0.037818,0.152639,0.000000,0.000000,0.000000,0.000000,3.000000e+00
Barcelona_rain_3h,8763.0,0.000439,0.003994,0.000000,0.000000,0.000000,0.000000,9.300000e-02
Valencia_snow_3h,8763.0,0.000205,0.011866,0.000000,0.000000,0.000000,0.000000,7.916667e-01
Madrid_weather_id,8763.0,773.527594,77.313315,211.000000,800.000000,800.000000,800.666667,8.040000e+02
Barcelona_weather_id,8763.0,765.979687,88.142235,200.666667,800.000000,800.333333,801.000000,8.040000e+02
Bilbao_pressure,8763.0,1017.739549,10.046124,971.333333,1013.000000,1019.000000,1024.000000,1.042000e+03
Seville_weather_id,8763.0,774.658818,71.940009,200.000000,800.000000,800.000000,800.000000,8.040000e+02
Valencia_pressure,6695.0,1012.051407,9.506214,972.666667,1010.333333,1015.000000,1018.000000,1.021667e+03
Seville_temp_max,8763.0,297.479527,8.875812,272.063000,291.312750,297.101667,304.150000,3.204833e+02
Madrid_pressure,8763.0,1010.316920,22.198555,927.666667,1012.333333,1017.333333,1022.000000,1.038000e+03
Valencia_temp_max,8763.0,291.337233,7.565692,269.888000,285.550167,291.037000,297.248333,3.142633e+02
Valencia_temp,8763.0,290.592152,7.162274,269.888000,285.150000,290.176667,296.056667,3.104267e+02
Bilbao_weather_id,8763.0,724.722362,115.846537,207.333333,700.333333,800.000000,801.666667,8.040000e+02
Seville_temp,8763.0,293.978903,7.920986,272.063000,288.282917,293.323333,299.620333,3.149767e+02
Valencia_humidity,8763.0,65.247727,19.262322,10.333333,51.333333,67.000000,81.333333,1.000000e+02
Valencia_temp_min,8763.0,289.867648,6.907402,269.888000,284.783333,289.550000,294.820000,3.102720e+02
Barcelona_temp_max,8763.0,291.157644,7.273538,272.150000,285.483333,290.150000,296.855000,3.140767e+02
Madrid_temp_max,8763.0,289.540309,9.752047,264.983333,282.150000,288.116177,296.816667,3.144833e+02
Barcelona_temp,8763.0,289.855459,6.528111,270.816667,284.973443,289.416667,294.909000,3.073167e+02
Bilbao_temp_min,8763.0,285.017973,6.705672,264.483333,280.085167,284.816667,289.816667,3.098167e+02
Bilbao_temp,8763.0,286.422929,6.818682,267.483333,281.374167,286.158333,291.034167,3.107100e+02
Barcelona_temp_min,8763.0,288.447422,6.102593,269.483333,284.150000,288.150000,292.966667,3.048167e+02
Bilbao_temp_max,8763.0,287.966027,7.105590,269.063000,282.836776,287.630000,292.483333,3.179667e+02
Seville_temp_min,8763.0,291.633356,8.178220,270.150000,285.816667,290.816667,297.150000,3.148167e+02
Madrid_temp,8763.0,288.419439,9.346796,264.983333,281.404281,287.053333,295.154667,3.131333e+02
Madrid_temp_min,8763.0,287.202203,9.206237,264.983333,280.299167,286.083333,293.884500,3.103833e+02
load_shortfall_3h,8763.0,10673.857612,5218.046404,-6618.000000,7390.333333,11114.666667,14498.166667,3.190400e+04

In [12]:
# A look at the test data descriptive statistics
df_test.describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,2920.0,10222.500000,843.075718,8763.000000,9492.750000,10222.500000,10952.250000,11682.000000
Madrid_wind_speed,2920.0,2.457820,1.774838,0.000000,1.333333,2.000000,3.333333,13.333333
Bilbao_rain_1h,2920.0,0.067517,0.153381,0.000000,0.000000,0.000000,0.000000,1.600000
Valencia_wind_speed,2920.0,3.012785,1.996340,0.000000,1.666667,2.333333,4.000000,14.333333
Seville_humidity,2920.0,67.123516,20.611292,11.666667,52.000000,70.333333,85.000000,100.000000
Madrid_humidity,2920.0,62.644463,24.138393,8.000000,43.000000,63.000000,84.000000,100.000000
Bilbao_clouds_all,2920.0,43.355422,30.486298,0.000000,13.333333,45.000000,75.000000,97.333333
Bilbao_wind_speed,2920.0,2.283562,1.654787,0.000000,1.000000,1.666667,3.333333,10.666667
Seville_clouds_all,2920.0,15.477283,25.289197,0.000000,0.000000,0.000000,20.000000,93.333333
Bilbao_wind_deg,2920.0,162.643836,97.749873,0.000000,86.666667,140.000000,233.333333,360.000000
Barcelona_wind_speed,2920.0,2.518094,1.625507,0.000000,1.333333,2.000000,3.666667,12.666667
Barcelona_wind_deg,2920.0,178.979452,86.976503,0.000000,113.333333,176.666667,253.333333,343.333333
Madrid_clouds_all,2920.0,24.255822,29.430257,0.000000,0.000000,11.333333,40.000000,92.000000
Seville_wind_speed,2920.0,2.657192,1.788870,0.000000,1.333333,2.333333,3.666667,12.666667
Barcelona_rain_1h,2920.0,0.047397,0.162474,0.000000,0.000000,0.000000,0.000000,2.300000
Seville_rain_1h,2920.0,0.046164,0.193432,0.000000,0.000000,0.000000,0.000000,2.300000
Bilbao_snow_3h,2920.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Barcelona_pressure,2920.0,1015.317123,7.021445,988.333333,1012.000000,1016.000000,1019.333333,1037.000000
Seville_rain_3h,2920.0,0.000001,0.000074,0.000000,0.000000,0.000000,0.000000,0.004000
Madrid_rain_1h,2920.0,0.059863,0.193218,0.000000,0.000000,0.000000,0.000000,3.000000
Barcelona_rain_3h,2920.0,0.000006,0.000217,0.000000,0.000000,0.000000,0.000000,0.009667
Valencia_snow_3h,2920.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Madrid_weather_id,2920.0,758.820101,93.536025,262.500000,800.000000,800.000000,800.666667,804.000000
Barcelona_weather_id,2920.0,760.473307,98.009846,207.333333,800.000000,800.000000,801.000000,804.000000
Bilbao_pressure,2920.0,1016.709132,8.773784,975.000000,1013.333333,1017.666667,1022.000000,1040.000000
Seville_weather_id,2920.0,772.226294,75.727539,259.500000,800.000000,800.000000,800.333333,804.000000
Valencia_pressure,2466.0,1013.148351,6.528997,973.000000,1010.666667,1014.666667,1017.666667,1021.666667
Seville_temp_max,2920.0,291.589360,7.521748,273.816667,286.150000,290.483333,296.483333,315.150000
Madrid_pressure,2920.0,1016.240411,9.624074,943.000000,1013.666667,1017.333333,1021.333333,1036.000000
Valencia_temp_max,2920.0,291.439216,7.055448,273.816667,286.150000,291.150000,297.150000,310.150000
Valencia_temp,2920.0,291.377796,7.113243,273.816667,285.816667,291.150000,297.150000,310.150000
Bilbao_weather_id,2920.0,737.039079,106.129916,207.666667,702.000000,800.000000,802.000000,804.000000
Seville_temp,2920.0,290.746255,7.738131,272.350000,285.356667,289.540000,295.674167,314.816667
Valencia_humidity,2920.0,64.623916,18.355766,13.000000,52.000000,65.000000,79.333333,100.000000
Valencia_temp_min,2920.0,291.317184,7.176955,273.816667,285.816667,291.150000,297.150000,310.150000
Barcelona_temp_max,2920.0,290.695462,7.113599,273.816667,284.816667,290.150000,296.483333,309.483333
Madrid_temp_max,2920.0,288.888393,9.089699,269.816667,281.483333,287.483333,295.483333,313.483333
Barcelona_temp,2920.0,289.911289,7.119411,272.650000,284.307500,289.483333,295.816667,308.150000
Bilbao_temp_min,2920.0,284.920684,6.803424,266.483333,280.150000,284.483333,289.816667,307.483333
Bilbao_temp,2920.0,286.522375,6.492355,268.120000,281.778333,286.265000,291.119167,308.966667
Barcelona_temp_min,2920.0,289.124971,7.168049,271.483333,283.483333,288.816667,295.150000,306.816667
Bilbao_temp_max,2920.0,288.483641,6.221324,270.138667,284.150000,288.483333,292.816667,310.816667
Seville_temp_min,2920.0,290.152431,7.906915,271.150000,284.483333,289.150000,295.150000,314.483333
Madrid_temp,2920.0,287.869763,8.977511,268.713333,280.816667,286.396667,294.452500,312.223333
Madrid_temp_min,2920.0,286.618130,8.733163,267.816667,279.816667,285.483333,293.150000,310.150000

Observations:

1. Assessment indicates the presence of an anomaly with the rainfall levels of barcelona in the train dataset. (high rainfall level and there wasn't any rain that day as determined from online records) 
2. The windspeed for valencia.(max speed 52 is too high, other cities had a maximum wind speed of 12, normal windspeed levels fall between the ranges of 10 to 19 on average)
3. There are no percentiles for rain_1h and snow_1h
4. There are no percentiles for rain_3h and snow_3h

In [13]:
df_train.kurtosis().T

C:\Users\PC\AppData\Local\Temp\ipykernel_16972\1940544335.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df_train.kurtosis().T

Unnamed: 0                -1.200000
Madrid_wind_speed          2.036462
Bilbao_rain_1h            32.904656
Valencia_wind_speed       35.645426
Seville_humidity          -1.017983
Madrid_humidity           -1.167537
Bilbao_clouds_all         -1.533417
Bilbao_wind_speed          3.631565
Seville_clouds_all         2.155921
Bilbao_wind_deg           -1.083530
Barcelona_wind_speed       1.493635
Barcelona_wind_deg        -0.959160
Madrid_clouds_all          0.142079
Seville_wind_speed         1.398580
Barcelona_rain_1h        101.578931
Seville_rain_1h           93.840746
Bilbao_snow_3h           806.128471
Barcelona_pressure      3687.564230
Seville_rain_3h          413.136592
Madrid_rain_1h            76.584491
Barcelona_rain_3h        187.800460
Valencia_snow_3h        4089.323165
Madrid_weather_id          9.259047
Barcelona_weather_id       5.701882
Bilbao_pressure            1.825323
Seville_weather_id        10.710308
Valencia_pressure          2.211823
Seville_temp_max          -0.515989
Madrid_pressure            2.216199
Valencia_temp_max         -0.613755
Valencia_temp             -0.643793
Bilbao_weather_id          0.067814
Seville_temp              -0.504132
Valencia_humidity         -0.734345
Valencia_temp_min         -0.599551
Barcelona_temp_max        -0.728757
Madrid_temp_max           -0.662861
Barcelona_temp            -0.696555
Bilbao_temp_min           -0.230342
Bilbao_temp               -0.086363
Barcelona_temp_min        -0.474890
Bilbao_temp_max            0.283366
Seville_temp_min          -0.475564
Madrid_temp               -0.612299
Madrid_temp_min           -0.666646
load_shortfall_3h         -0.118999
dtype: float64

Observations:
The following columns have high kurtosis;

>Bilbao_rain_1h       =     32.904656  
>Valencia_wind_speed     =  35.645426  
>Bilbao_wind_speed       =   3.631565  
>Seville_rain_1h          = 93.840746  
>Bilbao_snow_3h         =  806.128471  
>Barcelona_pressure   =   3687.564230  
>Seville_rain_3h       =   413.136592  
>Madrid_rain_1h        =    76.584491  
>Barcelona_rain_3h     =   187.800460  
>Valencia_snow_3h       = 4089.323165  
>Madrid_weather_id      =    9.259047  
>Barcelona_weather_id    =   5.701882  
>Seville_weather_id       = 10.710308

In [14]:
df_test.kurtosis()

C:\Users\PC\AppData\Local\Temp\ipykernel_16972\3512821554.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df_test.kurtosis()

Unnamed: 0                -1.200000
Madrid_wind_speed          2.567383
Bilbao_rain_1h            16.905396
Valencia_wind_speed        2.100244
Seville_humidity          -0.710306
Madrid_humidity           -1.134569
Bilbao_clouds_all         -1.488942
Bilbao_wind_speed          2.306390
Seville_clouds_all         1.417797
Bilbao_wind_deg           -1.017392
Barcelona_wind_speed       1.410571
Barcelona_wind_deg        -0.956300
Madrid_clouds_all         -0.566527
Seville_wind_speed         2.369604
Barcelona_rain_1h         52.069367
Seville_rain_1h           48.243445
Bilbao_snow_3h             0.000000
Barcelona_pressure         1.175366
Seville_rain_3h         2920.000000
Madrid_rain_1h            41.250278
Barcelona_rain_3h       1642.238858
Valencia_snow_3h           0.000000
Madrid_weather_id          5.349404
Barcelona_weather_id       6.056749
Bilbao_pressure            1.866927
Seville_weather_id         9.557456
Valencia_pressure          4.966557
Seville_temp_max          -0.259161
Madrid_pressure           14.027856
Valencia_temp_max         -0.849111
Valencia_temp             -0.860609
Bilbao_weather_id          1.594178
Seville_temp              -0.234510
Valencia_humidity         -0.690135
Valencia_temp_min         -0.866402
Barcelona_temp_max        -0.842246
Madrid_temp_max           -0.730728
Barcelona_temp            -0.879454
Bilbao_temp_min           -0.464116
Bilbao_temp               -0.403283
Barcelona_temp_min        -0.871643
Bilbao_temp_max           -0.324173
Seville_temp_min          -0.220734
Madrid_temp               -0.720287
Madrid_temp_min           -0.764179
dtype: float64

Observations:
The following columns have high kurtosis;

>Bilbao_rain_1h         =   16.905396  
>Barcelona_rain_1h       =  52.069367  
>Seville_rain_1h       =    48.243445  
>Seville_rain_3h       =  2920.000000  
>Madrid_rain_1h       =     41.250278  
>Barcelona_rain_3h     =  1642.238858  
>Valencia_pressure     =     4.966557  
>Madrid_pressure       =    14.027856

In [15]:
df_train.skew().T

C:\Users\PC\AppData\Local\Temp\ipykernel_16972\2179370390.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df_train.skew().T

Unnamed: 0               0.000000
Madrid_wind_speed        1.441144
Bilbao_rain_1h           5.222802
Valencia_wind_speed      3.499637
Seville_humidity        -0.310175
Madrid_humidity         -0.057378
Bilbao_clouds_all       -0.053085
Bilbao_wind_speed        1.716914
Seville_clouds_all       1.814452
Bilbao_wind_deg          0.226927
Barcelona_wind_speed     1.057331
Barcelona_wind_deg      -0.180001
Madrid_clouds_all        1.246745
Seville_wind_speed       1.151006
Barcelona_rain_1h        8.726988
Seville_rain_1h          8.067341
Bilbao_snow_3h          26.177568
Barcelona_pressure      57.979664
Seville_rain_3h         19.342574
Madrid_rain_1h           7.074308
Barcelona_rain_3h       12.696605
Valencia_snow_3h        63.298084
Madrid_weather_id       -3.107722
Barcelona_weather_id    -2.584011
Bilbao_pressure         -0.999642
Seville_weather_id      -3.275574
Valencia_pressure       -1.705162
Seville_temp_max        -0.033931
Madrid_pressure         -1.850768
Valencia_temp_max        0.082672
Valencia_temp            0.057476
Bilbao_weather_id       -1.234844
Seville_temp             0.157238
Valencia_humidity       -0.305757
Valencia_temp_min        0.081832
Barcelona_temp_max       0.276925
Madrid_temp_max          0.298707
Barcelona_temp           0.128095
Bilbao_temp_min          0.194912
Bilbao_temp              0.293686
Barcelona_temp_min      -0.018057
Bilbao_temp_max          0.393932
Seville_temp_min         0.265482
Madrid_temp              0.304123
Madrid_temp_min          0.275083
load_shortfall_3h       -0.384847
dtype: float64

***Observations:***  
**The following columns have High Positve Skew;**  

Madrid_wind_speed        1.441144  
< Bilbao_rain_1h           5.222802 >  
< Valencia_wind_speed      3.499637 >  
< Bilbao_wind_speed        1.716914 >  
Seville_clouds_all       1.814452  
Madrid_clouds_all        1.246745  
Seville_wind_speed       1.151006  
Barcelona_rain_1h        8.726988  
< Seville_rain_1h          8.067341 >  
Bilbao_snow_3h          26.177568  
Barcelona_pressure      57.979664  
Seville_rain_3h         19.342574  
< Madrid_rain_1h           7.074308 >  
< Barcelona_rain_3h       12.696605 >  
< Valencia_snow_3h        63.298084 >  

**The following columns have High Negative Skew;**  

Madrid_weather_id       -3.107722  
Barcelona_weather_id    -2.584011  
Seville_weather_id      -3.275574  
Valencia_pressure       -1.705162  
Madrid_pressure         -1.850768  
Bilbao_weather_id       -1.234844

In [16]:
df_test.skew()

C:\Users\PC\AppData\Local\Temp\ipykernel_16972\2005478040.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df_test.skew()

Unnamed: 0               0.000000
Madrid_wind_speed        1.494269
Bilbao_rain_1h           3.404307
Valencia_wind_speed      1.328872
Seville_humidity        -0.508637
Madrid_humidity         -0.135537
Bilbao_clouds_all       -0.124933
Bilbao_wind_speed        1.381876
Seville_clouds_all       1.628723
Bilbao_wind_deg          0.322569
Barcelona_wind_speed     1.080200
Barcelona_wind_deg      -0.029036
Madrid_clouds_all        0.925034
Seville_wind_speed       1.346297
Barcelona_rain_1h        5.989675
Seville_rain_1h          6.269205
Bilbao_snow_3h           0.000000
Barcelona_pressure      -0.572509
Seville_rain_3h         54.037024
Madrid_rain_1h           5.211963
Barcelona_rain_3h       40.017330
Valencia_snow_3h         0.000000
Madrid_weather_id       -2.439600
Barcelona_weather_id    -2.577583
Bilbao_pressure         -0.952458
Seville_weather_id      -3.103741
Valencia_pressure       -1.779108
Seville_temp_max         0.473503
Madrid_pressure         -2.608926
Valencia_temp_max        0.019499
Valencia_temp            0.013895
Bilbao_weather_id       -1.597967
Seville_temp             0.447950
Valencia_humidity       -0.254626
Valencia_temp_min        0.003098
Barcelona_temp_max       0.122526
Madrid_temp_max          0.380357
Barcelona_temp           0.049914
Bilbao_temp_min          0.225491
Bilbao_temp              0.193047
Barcelona_temp_min      -0.018895
Bilbao_temp_max          0.103054
Seville_temp_min         0.423952
Madrid_temp              0.385689
Madrid_temp_min          0.355444
dtype: float64

***Observations:***  
**The following columns have High Positve Skew;**  

Madrid_wind_speed        1.441144  
< Bilbao_rain_1h           5.222802 >  
< Valencia_wind_speed      3.499637 >  
< Bilbao_wind_speed        1.716914 >  
Seville_clouds_all       1.814452  
Madrid_clouds_all        1.246745  
Seville_wind_speed       1.151006  
Barcelona_rain_1h        8.726988  
< Seville_rain_1h          8.067341 >  
Bilbao_snow_3h          26.177568  
Barcelona_pressure      57.979664  
Seville_rain_3h         19.342574  
< Madrid_rain_1h           7.074308 >  
< Barcelona_rain_3h       12.696605 >  
< Valencia_snow_3h        63.298084 >  

**The following columns have High Negative Skew;**  

Madrid_weather_id       -3.107722  
Barcelona_weather_id    -2.584011  
Seville_weather_id      -3.275574  
Valencia_pressure       -1.705162  
Madrid_pressure         -1.850768  
Bilbao_weather_id       -1.234844

In [ ]:
# plot relevant feature interactions

In [ ]:
plt.figure(figsize = [10,5])
df_train.skew(axis=0, skipna=True).plot();

In [ ]:
plt.figure(figsize = [10,5])
df_train.kurtosis(axis=0, skipna=True).plot();

In [ ]:
sns.set(rc={'figure.figsize':(10,10)})

#define plotting region (2 rows, 2 columns)
fig, axes = plt.subplots(5, 2)

#create boxplot in each subplot
sns.scatterplot(data=df_train, y='Bilbao_rain_1h', x='load_shortfall_3h', ax=axes[0,0])
sns.scatterplot(data=df_train, y='Valencia_wind_speed', x='load_shortfall_3h', ax=axes[0,1])
sns.scatterplot(data=df_train, y='Bilbao_wind_speed', x='load_shortfall_3h', ax=axes[1,0])
sns.scatterplot(data=df_train, y='Seville_rain_1h', x='load_shortfall_3h', ax=axes[1,1])
sns.scatterplot(data=df_train, y='Bilbao_snow_3h', x='load_shortfall_3h', ax=axes[2,0])
sns.scatterplot(data=df_train, y='Barcelona_pressure', x='load_shortfall_3h', ax=axes[2,1])
sns.scatterplot(data=df_train, y='Seville_rain_3h', x='load_shortfall_3h', ax=axes[3,0])
sns.scatterplot(data=df_train, y='Madrid_rain_1h', x='load_shortfall_3h', ax=axes[3,1])
sns.scatterplot(data=df_train, y='Barcelona_rain_3h', x='load_shortfall_3h', ax=axes[4,0])
sns.scatterplot(data=df_train, y='Valencia_snow_3h', x='load_shortfall_3h', ax=axes[4,1]);

In [ ]:
# Visualizing the correlation
fig = plt.figure(figsize=(10,8));
ax = fig.add_subplot(111);
plot_corr(df_train.corr(), xnames = df_train.corr().columns, ax = ax, );

In [ ]:
plt.figure(figsize=[35,15])
sns.heatmap(df_train.corr(), vmin=-1, vmax=1 ,annot=True);

In [ ]:
# evaluate correlation

In [ ]:
# have a look at feature distributions

<a id="four"></a>
## 4. Data Engineering
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Data engineering ⚡ |
| :--------------------------- |
| In this section you are required to: clean the dataset, and possibly create new features - as identified in the EDA phase. |

---

In [ ]:
# remove missing values/ features

In [ ]:
df_train = df_train.reindex(sorted(df_train.columns), axis=1)

In [ ]:
df_train.columns = df_train.columns.str.lower()

In [ ]:
df_train.columns

In [ ]:
df_train.drop(['unnamed: 0', 'barcelona_weather_id', 'bilbao_weather_id', 'madrid_weather_id', 'seville_weather_id'], axis = 1, inplace = True)

In [ ]:
df_train.head()

In [ ]:
def sub_outliers_pressure(df, col):
    upper_limit = df[col].mean() + 3*df[col].std()
    lower_limit = df[col].mean() - 3*df[col].std()
    df[col] = np.where(df[col] > 1052,
        upper_limit,
        np.where(
            df[col] < 950,
            950,
            df[col]
        )
    )
    return df.describe()

In [ ]:
def sub_outliers_wind(df, col):
    upper_limit = df[col].mean() + 3*df[col].std()
    lower_limit = df[col].mean() - 3*df[col].std()
    df[col] = np.where(df[col] > 19,
        upper_limit,
            df[col]
    )
    
    return df.describe()

In [ ]:
def sub_outliers_rain(df, col):
    upper_limit = df[col].mean() + 3*df[col].std()
    lower_limit = df[col].mean() - 3*df[col].std()
    df[col] = np.where(df[col] > 1052,
        upper_limit,
        
    )
    return df.describe()

In [ ]:
#sub_outliers(df_train, 'bilbao_rain_1h')
sub_outliers_wind(df_train, 'valencia_wind_speed')
sub_outliers_wind(df_train, 'bilbao_wind_speed')
#sub_outliers(df_train, 'seville_rain_1h')
#sub_outliers(df_train, 'bilbao_snow_3h')
sub_outliers_pressure(df_train, 'barcelona_pressure')
#sub_outliers(df_train, 'seville_rain_3h')
#sub_outliers(df_train, 'madrid_rain_1h')
#sub_outliers(df_train, 'barcelona_rain_3h')
#sub_outliers(df_train, 'valencia_snow_3h')

In [ ]:
df_train['barcelona_pressure'].value_counts()

In [ ]:
df_train.kurtosis().T

In [ ]:
df_train['valencia_pressure'].fillna(df_train['valencia_pressure'].mean(), inplace = True)

In [ ]:
df_train.skew()

In [ ]:
plt.figure(figsize = [10,5])
df_train.skew(axis=0, skipna=True).plot(rotation=90);

In [ ]:
# create new features

In [ ]:
#creating a level category for the wind degree columns
classes = {
    "level_1" : [0,36],
    "level_2" : [36,72],
    "level_3" : [72,108],
    "level_4" : [108,144],
    "level_5" : [144,180],
    "level_6" : [180,216],
    "level_7" : [216,252],
    "level_8" : [252,288],
    "level_9" : [288,324],
    "level_10" : [324,360]
}

In [ ]:
#A function that changes the wind degree columns to categorical
def change_level(df, column_name, dictionary):
    row = 0
    for x in df[column_name]:
        for key, value in dictionary.items():
            if x == 0.0:
                df.at[row, column_name] = key
            if x > value[0] and x <= value[1]:
                df.at[row, column_name] = key
        row += 1
    
    return

In [ ]:
change_level(df_train, "barcelona_wind_deg", classes)

In [ ]:
change_level(df_train, "bilbao_wind_deg", classes)

In [ ]:
df_train['bilbao_wind_deg'].value_counts()

In [ ]:
#creating the level boundaries for the pressure columns
levels = np.arange(950, 1050 +1, 4)
levels

In [ ]:
#create an empty dictionary for the pressure levels
pressure_dict = {}

In [ ]:
#creating and adding the pressure levels to the dictionary
for i in range(len(levels) - 1):
    pressure_dict['sp' + str(i+1)] = [levels[i], levels[i+1]]
pressure_dict

In [ ]:
change the values for all the pressure columns in the train dataset to their respective categories
for column in df_train[[x for x in df_train.columns if 'pressure' in x and 'seville' not in x]].columns:
    change_level(df_train, column, pressure_dict)

In [ ]:
change_level(df_train, 'barcelona_pressure', pressure_dict)
df_train['barcelona_pressure'].value_counts()

In [ ]:
# Visualizing the correlation
fig = plt.figure(figsize=(10,10));
ax = fig.add_subplot(111);
plot_corr(df_train.corr(), xnames = df_train.corr().columns, ax = ax, );

In [ ]:
plt.figure(figsize=[35,25])
sns.set(font_scale=1.4)
train_heatmap = sns.heatmap(df_train.corr(), vmin=-1, vmax=1 ,annot=True)
#train_heatmap = sns.diverging_palette(h_neg=210, h_pos=350, s=90, l=30, as_cmap=True)
train_heatmap.set_title('Correlation Heatmap', fontdict={'fontsize':20}, pad=12);

In [ ]:
#creating dummies for the pressure columns
seville_pressure_dummy = pd.get_dummies(df_train['seville_pressure'])
barcelona_pressure_dummy = pd.get_dummies(df_train['barcelona_pressure'])
bilbao_pressure_dummy = pd.get_dummies(df_train['bilbao_pressure'])
madrid_pressure_dummy = pd.get_dummies(df_train['madrid_pressure'])
valencia_pressure_dummy = pd.get_dummies(df_train['valencia_pressure'])
barcelona_pressure_dummy

In [ ]:
#checking dummy df for duplicates
seville_pressure_dummy['check'] = seville_pressure_dummy.sum(axis=1)
barcelona_pressure_dummy['check'] = barcelona_pressure_dummy.sum(axis=1)
bilbao_pressure_dummy['check'] = bilbao_pressure_dummy.sum(axis=1)
madrid_pressure_dummy['check'] = madrid_pressure_dummy.sum(axis=1)
valencia_pressure_dummy['check'] = valencia_pressure_dummy.sum(axis=1)

In [ ]:
seville_pressure_dummy['check'].unique()

In [ ]:
seville_pressure_dummy = seville_pressure_dummy.drop(['check'],axis=1)
barcelona_pressure_dummy = barcelona_pressure_dummy.drop(['check'],axis=1)
bilbao_pressure_dummy = bilbao_pressure_dummy.drop(['check'],axis=1)
madrid_pressure_dummy = madrid_pressure_dummy.drop(['check'],axis=1)
valencia_pressure_dummy = valencia_pressure_dummy.drop(['check'],axis=1)
barcelona_pressure_dummy

In [ ]:
df_train.drop(['seville_pressure'], axis = 1)
df_train.drop(['barcelona_pressure'], axis = 1)
df_train.drop(['bilbao_pressure'], axis = 1)
df_train.drop(['madrid_pressure'], axis = 1)
df_train.drop(['valencia_pressure'], axis = 1)

In [ ]:
svp_lvl1 = seville_pressure_dummy.loc[:, 'sp1': 'sp17'].max(axis=1)
svp_lvl2 = seville_pressure_dummy.loc[:, 'sp18': 'sp24'].max(axis=1)
svp_lvl3 = seville_pressure_dummy.loc[:, 'sp25':].max(axis=1)

#bcp_lvl1 = barcelona_pressure_dummy.loc[:, '950.0': 'sp16'].max(axis=1)
#bcp_lvl2 = barcelona_pressure_dummy.loc[:, 'sp17': 'sp23'].max(axis=1)
#bcp_lvl3 = barcelona_pressure_dummy.loc[:, 'sp7':].max(axis=1)

#bbp_lvl1 = bilbao_pressure_dummy.loc[:, 'sp1': 'sp17'].max(axis=1)
#bbp_lvl2 = bilbao_pressure_dummy.loc[:, 'sp18': 'sp24'].max(axis=1)
#bbp_lvl3 = bilbao_pressure_dummy.loc[:, 'sp25':].max(axis=1)

#mdp_lvl1 = madrid_pressure_dummy.loc[:, 'sp1': 'sp17'].max(axis=1)
#mdp_lvl2 = madrid_pressure_dummy.loc[:, 'sp18': 'sp24'].max(axis=1)
#mdp_lvl3 = madrid_pressure_dummy.loc[:, 'sp25':].max(axis=1)

#vlp_lvl1 = valencia_pressure.loc[:, 'sp1': 'sp17'].max(axis=1)
#vlp_lvl2 = valencia_pressure.loc[:, 'sp18': 'sp24'].max(axis=1)
#vlp_lvl3 = valencia_pressure.loc[:, 'sp25':].max(axis=1)

In [ ]:
df_train = pd.concat([df_train, svp_lvl1, svp_lvl2, svp_lvl3], axis=1)
df_train = pd.concat([df_train, bcp_lvl1, bcp_lvl2, bcp_lvl3], axis=1)
df_train = pd.concat([df_train, bbp_lvl1, bbp_lvl2, bbp_lvl3], axis=1)
df_train = pd.concat([df_train, mdp_lvl1, mdp_lvl2, mdp_lvl3], axis=1)
df_train = pd.concat([df_train, vlp_lvl1, vlp_lvl2, vlp_lvl3], axis=1)

In [ ]:
df_train.columns

In [ ]:
column_names = [  'barcelona_pressure',    'barcelona_rain_1h',    'barcelona_rain_3h',
             'barcelona_temp',   'barcelona_temp_max',   'barcelona_temp_min',
         'barcelona_wind_deg', 'barcelona_wind_speed',    'bilbao_clouds_all',
            'bilbao_pressure',       'bilbao_rain_1h',       'bilbao_snow_3h',
                'bilbao_temp',      'bilbao_temp_max',      'bilbao_temp_min',
            'bilbao_wind_deg',    'bilbao_wind_speed',    'madrid_clouds_all',
            'madrid_humidity',      'madrid_pressure',       'madrid_rain_1h',
                'madrid_temp',      'madrid_temp_max',      'madrid_temp_min',
          'madrid_wind_speed',   'seville_clouds_all',     'seville_humidity',
           'seville_pressure',      'seville_rain_1h',      'seville_rain_3h',
               'seville_temp',     'seville_temp_max',     'seville_temp_min',
         'seville_wind_speed',    'valencia_humidity',    'valencia_pressure',
           'valencia_snow_3h',        'valencia_temp',    'valencia_temp_max',
          'valencia_temp_min',    'valencia_wind_deg',  'valencia_wind_speed',
          'load_shortfall_3h',                 'time',               'sp_lvl1',
                            'sp_lvl2',                      'sp_lvl3', 'bcp_lvl1',
                'bcp_lvl2', 'bcp_lvl3', 'bbp_lvl1', 'bbp_lvl2', 'bbp_lvl3', 'mdp_lvl1', 'mdp_lvl2', 'mdp_lvl3',
               'vlp_lvl1', 'vlp_lvl2', 'vlp_lvl3']

In [ ]:
df_train.columns = column_names

In [ ]:
df_train.columns

In [ ]:
# engineer existing features

<a id="five"></a>
## 5. Modelling
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Modelling ⚡ |
| :--------------------------- |
| In this section, you are required to create one or more regression models that are able to accurately predict the thee hour load shortfall. |

---

In [ ]:
# split data

In [ ]:
# create targets and features dataset
X = df_train.drop(['time',
 'valencia_wind_deg',
 'bilbao_wind_deg',
 'barcelona_wind_deg',
 'seville_pressure',
 'barcelona_pressure',
 'bilbao_pressure',
 'valencia_pressure',
 'madrid_pressure', 'load_shortfall_3h'], axis=1)

In [ ]:
y = df_train['load_shortfall_3h'].astype('int')

In [ ]:
# create one or more ML models
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression
lg = linear_model.LogisticRegression(solver='lbfgs', max_iter=100)

In [ ]:
lg.fit(X, y)

In [ ]:
lg.coef_

In [ ]:
lg.intercept_

In [ ]:
X_test = df_test.drop(['time',
 'valencia_wind_deg',
 'bilbao_wind_deg',
 'barcelona_wind_deg',
 'seville_pressure',
 'barcelona_pressure',
 'bilbao_pressure',
 'valencia_pressure',
 'madrid_pressure'], axis=1)

In [ ]:
# evaluate one or more ML models

<a id="six"></a>
## 6. Model Performance
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Model performance ⚡ |
| :--------------------------- |
| In this section you are required to compare the relative performance of the various trained ML models on a holdout dataset and comment on what model is the best and why. |

---

In [ ]:
# Compare model performance

In [ ]:
# Choose best model and motivate why it is the best choice

<a id="seven"></a>
## 7. Model Explanations
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Model explanation ⚡ |
| :--------------------------- |
| In this section, you are required to discuss how the best performing model works in a simple way so that both technical and non-technical stakeholders can grasp the intuition behind the model's inner workings. |

---

In [ ]:
# discuss chosen methods logic